"""add task description

Revision ID: d64e064a82cd
Revises: 1b64fd5fa0c6
Create Date: 2026-09-17 15:15:29.549973

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d64e064a82cd"
down_revision: Union[str, Sequence[str], None] = "1b64fd5fa0c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "description")
    # ### end Alembic commands ###
