from typing import Protocol
from uuid import UUID

from taskflow.task import Task


class TaskRepository(Protocol):
    """Schnittstelle für Task-Repositories."""

    def save(self, tasks: list[Task]) -> None: ...
    def get_all(self) -> list[Task]: ...
    def get_by_id(self, task_id: UUID) -> Task | None: ...
    def add(self, task: Task) -> None: ...
    def update(self, task: Task) -> None: ...
    def delete(self, task_id: UUID) -> None: ...
